<?php
namespace app\controllers;
use app\m\News;
use yii\rest\ActiveController;
use yii\web\Response;

class BaseController extends ActiveController//继承
{


public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
    // 指定允许其他域名访问
    header('Access-Control-Allow-Origin:*');
    // 响应类型
    header('Access-Control-Allow-Methods:GET,POST');
    header('Access-Control-Allow-Headers:x-requested-with,content-type');

}

//设置默认输出格式为json
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors;
    }
}