<?php
namespace app\controllers;
use app\m\News;
use yii\rest\ActiveController;
use yii\web\Response;

class UserController extends ActiveController//继承
{

    //模型类的位置：m/Users
    public $modelClass = 'app\m\Users';
    /*重写父类方法
       * public function actions()
      {
          $actions= parent::actions(); // TODO: Change the autogenerated stub
          unset($actions['index']);
          return $actions;
      }
      public function actionIndex(){//可以自定义访问方法
          echo 'xiaoping';
      }*/


    //设置默认输出格式为json
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors;
    }

}