<?php
namespace app\controllers;

use app\m\Uploader;

use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class VedioController extends ComBaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation=false;
    }

    function actionUploadpic()
    {
        $result=new \stdClass();
        $result->name="";
        $result->status=0;
        $result->url="";


        if (Yii::$app->request->isPost) {


            $model = new Uploader();

            if (Yii::$app->request->isPost) {
                $model->imageFile = UploadedFile::getInstance($model, 'file');
                $getUploadResult=$model->upload();
                if ($getUploadResult) {
                    // 文件上传成功
                    $result->name=$getUploadResult;
                    $result->status=1;
                    $result->url="http://localhost:9090/images/vedios/".$getUploadResult.".".$model->imageFile->extension;

                }
            }


        }


        return json_encode($result);
    }
}